on:
  pull_request:
    types:
      - closed

jobs:
  apply-dev-plan:
    uses: jingood2/tf-template/.github/workflows/apply-tf-plan.yml@main
    with:
      path: tfplan
      gh_environment: dev
      tf_version: 1.3.0
    secrets:
      aws_client_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_client_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  apply-stage-plan:
    needs: apply-dev-plan
    uses: jingood2/tf-template/.github/workflows/apply-tf-plan.yml@main
    with:
      path: tfplan
      gh_environment: stage
      tf_version: 1.3.0
    secrets:
      aws_client_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_client_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  apply-prod-plan:
    needs: apply-stage-plan
    uses: jingood2/tf-template/.github/workflows/apply-tf-plan.yml@main
    with:
      path: tfplan
      gh_environment: prod
      tf_version: 1.3.0
    secrets:
      aws_client_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_client_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}