
name: Terraform CICD Workflow

on:
  pull_request:
    branches:
      - main
  
  env:
    AWS_SECRET_KEY_ID: ${{ secrets.AWS_SECRET_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:
  plan_dev:
    uses: ./.github/workflows/plan-workflow.yml
    with:
      gh_environment: dev
      enable_TFSEC: true
    secrets:
      AWS_SECRET_KEY_ID: ${{ env.AWS_SECRET_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

  deploy_dev:
    needs: [plan_dev]
    uses: ./.github/workflows/apply-workflow.yml
    with:
      path: tfplan
      gh_environment: dev
      tf_version: 1.3.0

  plan_prod:
    uses: ./.github/workflows/plan-workflow.yml
    with:
      gh_environment: prod
      enable_TFSEC: false
    secrets:
      AWS_SECRET_KEY_ID: ${{ env.AWS_SECRET_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

  deploy_prod:
    if: github.event.label.name == 'prod'
    needs: [deploy_dev, plan_prod]
    uses: ./.github/workflows/apply-workflow.yml
    with:
      path: tfplan
      gh_environment: prod
      tf_version: 1.3.0
  
  destroy_dev:
    needs: [deploy_dev]
    uses: ./.github/workflows/cleanup.yml
    with:
      gh_environment: dev
      enable_destroy: true
  
  destroy_prod:
    if: github.event.label.name == 'prod'
    needs: [deploy_prod]
    uses: ./.github/workflows/cleanup.yml
    with:
      gh_environment: dev
      enable_destroy: true
  