
name: Terraform CICD Workflow

on:
  pull_request:
    #types:
    #  - opened
    #  - reopened
    #  - synchronize
    #  - closed
    branches:
      - main

jobs:
  plan_dev:
    uses: ./.github/workflows/plan-workflow.yml
    with:
      gh_environment: dev
      enable_TFSEC: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy_dev:
    needs: [plan_dev]
    uses: ./.github/workflows/apply-workflow.yml
    with:
      path: tfplan
      gh_environment: dev
      tf_version: 1.3.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  plan_prod:
    uses: ./.github/workflows/plan-workflow.yml
    with:
      gh_environment: prod
      enable_TFSEC: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy_prod:
    if: github.event.pull_request.merged 
    needs: [deploy_dev, plan_prod]
    uses: ./.github/workflows/apply-workflow.yml
    with:
      path: tfplan
      gh_environment: prod
      tf_version: 1.3.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
