name: Cleanup

on:
  workflow_call:
    inputs:
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: string
        default: dev
      enable_destroy:
        description: '(Optional) Enables TFSEC IaC scans and code quality checks on Terraform configurations'
        required: false
        type: boolean
        default: false

jobs:
  destroy_dev:
    runs-on: ubuntu-latest
    name: Destroy terraform workspace

    steps:
      - name: Checkout
        if: ${{ inputs.enable_destroy == true }}
        uses: actions/checkout@v3
      
      - name: Terraform Init
        id: init
        #run: terraform init
        run: terraform init -backend-config="environments/${{inputs.gh_environment}}-backend.conf"

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file=environments/${{inputs.gh_environment}}.auto.tfvars -out=destroy.tfplan

      - name: Terraform apply Destroy
        run: terraform apply destroy.tfplan

      # ToDo: Delete tfState in S3