name: Cleanup

on:
  workflow_call:
    inputs:
      gh_environment:
        description: 'Specifies the GitHub deployment environment.'
        required: false
        type: string
        default: dev
      enable_destroy:
        description: '(Optional) Enables TFSEC IaC scans and code quality checks on Terraform configurations'
        required: false
        type: boolean
        default: false

jobs:
  destroy_dev:
    runs-on: ubuntu-latest
    name: Destroy terraform workspace

    steps:
      - name: Checkout
        if: ${{ inputs.enable_destroy == true }}
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: true
          terraform_version: 1.3.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-northeast-2
          #role-to-assume: arn:aws:iam::783857413761:role/GithubOIDCRole
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Terraform Init
        id: init
        #run: terraform init
        run: terraform init -backend-config="backends/${{inputs.gh_environment}}.conf"

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -var-file=environments/${{inputs.gh_environment}}.auto.tfvars -out=destroy.tfplan

      - name: Terraform apply Destroy
        run: terraform apply destroy.tfplan

      # ToDo: Delete tfState in S3