name: Release

on:
  pull_request:
    types:
      - closed

permissions: write-all

jobs:
  update_release_draft:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.base_ref == 'main'
    steps:
      - name: Create Release
        uses: release-drafter/release-drafter@v5.22.0
        if: github.base_ref == 'main'
        with:
          publish: true
          commitish: main
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  destroy_dev:
    name: Cleanup dev
    if: github.event.pull_request.merged && github.base_ref == 'main'
    #if: github.event.pull_request.merged == true && github.event.label.name == 'cleanup-dev'
    uses: ./.github/workflows/cleanup.yml
    with:
      gh_environment: dev
      enable_destroy: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
